### ISSUE TITLE
Duplication of icons and Controls

### ISSUE THREAD

**Issue by rushden** [G-Stas/Volumey#25]
When using the software I seem to have duplicate icons and volume controls when I only have one instance open for some software such as zoom or flow launcher? 

![image](https://user-images.githubusercontent.com/59579092/160827011-20b7a332-a247-4255-a79c-be9dc1345de1.jpeg)

**Comment by G-Stas** [comment]
Does this happen for some specific apps or for all apps? Because some apps like Zoom, Skype or Discord create several audio sessions which control some specific audio from application. For example, Discord creates an additional audio session for controlling its push to talk click volume.

**Comment by G-Stas** [comment]
The default Windows panel doesn't display multiple sessions, even when there are several of them and they in fact control different things for the application. It only displays one slider for the entire application, which controls all sessions of the application. I don't like this decision.

EarTrumpet doesn't display multiple audio sessions by default, but you can right-click on the application and check whether there are several audio sessions or not.

Displaying multiple audio sessions in Volumey also might be due to displaying audio session even if it becomes inactive. I've changed this behavior, and it will be hidden when it becomes inactive now.

Please reopen if the issue is still there.
